
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Herrera
 */
public class Principal4 extends javax.swing.JFrame {

    /**
     * Creates new form Principal4
     */
    double v[];
    double v1[];
 
   
    public Principal4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtVectorV = new javax.swing.JTextField();
        txtVectorV1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtMostrar = new javax.swing.JButton();
        txtBorrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSuma = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResta = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("JasmineUPC", 3, 24)); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Iniciales"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Vector V");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 27, -1, -1));

        jLabel3.setText("Vcetor V1");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 52, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 120, 80));

        txtVectorV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVectorVActionPerformed(evt);
            }
        });
        txtVectorV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVectorVKeyTyped(evt);
            }
        });
        getContentPane().add(txtVectorV, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 80, -1));

        txtVectorV1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVectorV1KeyTyped(evt);
            }
        });
        getContentPane().add(txtVectorV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 80, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 100, -1));

        jButton2.setText("Llenar Manual");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jButton3.setText("Llenar Auto");
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 100, -1));

        txtMostrar.setText("Mostrar");
        txtMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMostrarActionPerformed(evt);
            }
        });
        jPanel2.add(txtMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 100, -1));

        txtBorrar.setText("Borrar");
        jPanel2.add(txtBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 100, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 140, 200));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Suma"));

        txtSuma.setColumns(20);
        txtSuma.setRows(5);
        jScrollPane1.setViewportView(txtSuma);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Resta"));

        txtResta.setColumns(20);
        txtResta.setRows(5);
        jScrollPane2.setViewportView(txtResta);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int vector;
        if (txtVectorV.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this,"Digite el vector v","ERROR",JOptionPane.ERROR_MESSAGE);
        
        txtVectorV.requestFocusInWindow();
        } else if (Integer.parseInt(txtVectorV.getText().trim())==0){
        JOptionPane.showMessageDialog(this, "El vector v no puede ser cero","ERROR",JOptionPane.ERROR_MESSAGE);
        txtVectorV.requestFocusInWindow();
        txtVectorV.selectAll();
        
        }else{
        vector = Integer.parseInt(txtVectorV.getText().trim());
        v= new double [vector];
        JOptionPane.showMessageDialog (this, "El vector se ha creado exitosamente");
        
        
        }
        int vectorv1;
        if (txtVectorV1.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this,"Digite el vector v1","ERROR",JOptionPane.ERROR_MESSAGE);
        
        txtVectorV1.requestFocusInWindow();
        } else if (Integer.parseInt(txtVectorV1.getText().trim())==0){
        JOptionPane.showMessageDialog(this, "El vector v1 no puede ser cero","ERROR",JOptionPane.ERROR_MESSAGE);
        txtVectorV1.requestFocusInWindow();
        txtVectorV1.selectAll();
        
        }else{
        vectorv1= Integer.parseInt(txtVectorV1.getText().trim());
        v= new double [vectorv1];
        JOptionPane.showMessageDialog (this, "El vector se ha creado exitosamente");
        
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtVectorVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVectorVActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtVectorVActionPerformed

    private void txtVectorVKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVectorVKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
          if (!Character.isDigit(c)){
          
          getToolkit().beep();
          evt.consume();
          }
    }//GEN-LAST:event_txtVectorVKeyTyped

    private void txtVectorV1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVectorV1KeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
          if (!Character.isDigit(c)){
          
          getToolkit().beep();
          evt.consume();
          }
    }//GEN-LAST:event_txtVectorV1KeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        double s;
        for (int i=0; i<v.length; i++) {
        s= Double.parseDouble(JOptionPane.showInputDialog(this, "Digite el elemento en la posicion"+i));
        v[i]=s;
        
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMostrarActionPerformed
        // TODO add your handling code here:
        int n = 0;
        int vI[]=new int[n];
        int vII[]=new int[n];
        int vSuma[]=new int[n];
        int vResta[]=new int[n];
        int[] vr=new int[n];
        int b = 0, s=0;
        int acum1=0, acum2=0, total=0, resta=0;
               
       
        
        
    
        
        
       
    
        

    }//GEN-LAST:event_txtMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton txtBorrar;
    private javax.swing.JButton txtMostrar;
    private javax.swing.JTextArea txtResta;
    private javax.swing.JTextArea txtSuma;
    private javax.swing.JTextField txtVectorV;
    private javax.swing.JTextField txtVectorV1;
    // End of variables declaration//GEN-END:variables
}
